defconfig: r2pro: disable net-support,add some options
- reset, gpio v2, scripting, OF_SYSTEM_SETUP for ram-detection

to avoid failed boot attempts via pxe/dhcp and "no ethernet found" message

squashed:

defconfig: r2pro: add more options for scripting/env

disable env-file due to override of soc-env and distroboot

defconfig: r2pro: disable CONFIG_OF_SYSTEM_SETUP because of build error

there is no rockchip implementation for it

https://elixir.bootlin.com/u-boot/v2023.04-rc2/C/ident/ft_system_setup

and it leads to linking error

LD u-boot
aarch64-linux-gnu-ld.bfd: boot/image-fdt.o: in function `image_setup_libfdt':
u-boot/boot/image-fdt.c:661: undefined reference to `ft_system_setup'
aarch64-linux-gnu-ld.bfd: cmd/fdt.o: in function `do_fdt':
u-boot/cmd/fdt.c:272: undefined reference to `ft_system_setup'
Segmentation fault (core dumped)
make: *** [Makefile:1753: u-boot] Error 139
make: *** Deleting file 'u-boot'
build failed!