build.sh: add build-script
squashed:
build.sh: avoid redundant PLAT in makeflags
build.sh: add backup function
build.sh: add do-not-automount flag for r3/r4
build.sh: support building emmc image for bpi-r3/r4
build.sh: do not write bl2 to first partition on emmc
build.sh: change emmc partitiontable back to sdmmc

gpt-partition starting at offset 0 breaks loading fip and editing with
sgdisk.

sdmmc partitiontable on emmc works

EC: 0000 0000 [2000]
BL2: v2.9(release):v2.9.0-349-g55576307fd8c emmc
ERROR:   Partition 'fip' not found
ERROR:   FIP boot source initialization failed with -2

using sdmmc-partition-table (with bl2) works:

EC: 0000 0000 [2000]
NOTICE:  BL2: v2.9(release):v2.9.0-349-g55576307fd8c emmc
NOTICE:  BL31: v2.9(release):v2.9.0-349-g55576307fd8c emmc
U-Boot 2024.01-rc1-bpi-00015-g1e4f6220a75b-dirty (Oct 24 2023 - 13:09:30 +0200)

build.sh: increase image to match emmc size
build.sh: exit if r64 binary file is missing
build.sh: add r64 emmc to createimg
build.sh: allow createimg for emmc on r64 ;)
build.sh: add r3mini with same settings as r3
build.sh: support uart boot (untested)
build.sh: only define files for install once
build.sh: add extraflags (for setting e.g. UBI=1 via conf)
build.sh: use different name for extraflags (e.g. ubi)