fix: readded missing lines to mt7986a-bpi-r3-emmc.dts to address the following error when cold-booting from the emmc.
NOTICE:  BL2: v2.6(release):c30a1caf827-dirty emmc
NOTICE:  BL2: Built : 20:12:40, Feb  7 2024
NOTICE:  WDT: disabled
NOTICE:  CPU: MT7986 (2000MHz)
NOTICE:  EMI: Using DDR4 settings
NOTICE:  EMI: Detected DRAM size: 2048MB
NOTICE:  EMI: complex R/W mem test passed
ERROR:   MSDC: Command has timed out with cmd=8, arg=0x1aa
ERROR:   MSDC: Command has timed out with cmd=17, arg=0x680000
ERROR:   MSDC: Command has timed out with cmd=17, arg=0x680000
ERROR:   BL2: Failed to load image id 3 (-5)