build.sh: change emmc partitiontable back to sdmmc
gpt-partition starting at offset 0 breaks loading fip and editing with
sgdisk.

sdmmc partitiontable on emmc works

EC: 0000 0000 [2000]
BL2: v2.9(release):v2.9.0-349-g55576307fd8c emmc
ERROR:   Partition 'fip' not found
ERROR:   FIP boot source initialization failed with -2

using sdmmc-partition-table (with bl2) works:

EC: 0000 0000 [2000]
NOTICE:  BL2: v2.9(release):v2.9.0-349-g55576307fd8c emmc
NOTICE:  BL31: v2.9(release):v2.9.0-349-g55576307fd8c emmc
U-Boot 2024.01-rc1-bpi-00015-g1e4f6220a75b-dirty (Oct 24 2023 - 13:09:30 +0200)