defconfig/uEnv: add defconfigs and environment files
squashed:

defconfig: r2pro: update defconfig

- add pcie options
- add additional options
- disable EFI_LOADER to make bootmenu clean

else bootmenu looks like this:

  *** U-Boot Boot Menu ***

      1. Boot from SD/EMMC.
      2. Standard Boot.
      mmc 1:2
      mmc 1:3
      U-Boot console

defconfig: r3: add pci and nvme commands

uenv: r3: add version field for supporting r3mini
uenv: r3/r4: add usenvme command
env: r3: add nmve bootmenu entry
uenv: r3: add function to load and start u-boot.bin
uenv: r3: drop root=ram for initrd
uenv: r3: set root for nvme too
uenv: r3: make useusb a bit more flexible (use env for part and path)
uenv: r4: drop initrd root override
uenv: r4: update useusb and add boot from nvme
defconfig: r4: update with pcie options
defconfig: r3: add pstore
defconfig: r4: add pstore
defconfig: r64/r3: add ext4 support too
env: r3: drop duplicate bootnetfit var
env: r3: drop duplicate askkernel and add asksetkernel and use it
env: r4: drop duplicate askkernel and bootnetfit
uenv: r4: add asksetkernel and use it where possible
uenv: r4: add bootnvme without asking for password
defconfig: r3/r4: add options for bootmedia detection/storage
defconfig: r3/r4: add some missing options in emmc configs
uenv: r3: fix uboot loadaddr (needs to be TEXT_BASE)
uenv: r3/r4: update builtin environment

uenv: r4: drop memory limit in bootargs/cmdline
this was a leftover from early development state where switch-,
ethernet- and ppe driver did not support 4G ram to get them to work.

defconfig: fix uuid-error
defconfig: add CONFIG_SERIAL_RX_BUFFER to avoid drop from bootmenu
defconfig: r3/r4: add ubi commands
uenv: r4: add support for phy variant (selecting right base dt)

currently only working with 6.15-rc

you have to add "is2g5=1" to uenv.txt on BPI-BOOT partition to enable

defconfig: r4: add i2c-mux support and options for eeprom
defconfig: r4: add missing mtd partition name
uenv: update network settings for using my r3 main router
uenv: r4: add r4pro variant
uenv: r4: add useubi and change fatload to load
uEnv: r4: add bootubi and bootnvme (without asking)

defconfig: all: change DEFAULT_ENV_FILE to ENV_DEFAULT_ENV_TEXT_FILE
see commit fb5235239aad43c41d528b2e6c8bd6c7b390cde1

defconfig: r64: fix undefined reference to `board_init'
70a4d1fa1ddb treewide: Remove empty board_init() function from all boards

defconfig: r4lite: fix undefined reference to `board_init'
defconfig: r3: add i2c+eeprom
defconfig: r3mini: add fs_loader for new phy driver
defconfig: r3mini: fix airoha phy driver

BPI-R3M> load usb 0:1 $loadaddr u-boot-r3mini_2026.01-rc5-bpi-arm64-emmc.bin
906328 bytes read in 78 ms (11.1 MiB/s)
BPI-R3M> go $loadaddr
\## Starting application at 0x46000000 ...

U-Boot 2026.01-rc5-bpi-00053-ga829474afe38-dirty (Dec 29 2025 - 13:48:07 +0100)

CPU:   MediaTek MT7986
Model: Bananapi BPi-R3 Mini
DRAM:  2 GiB
Core:  45 devices, 21 uclasses, devicetree: separate
MMC:   mmc@11230000: 0
Loading Environment from MMC... Reading from MMC(0)... *** Warning - bad CRC, using default environment

In:    serial@11002000
Out:   serial@11002000
Err:   serial@11002000
Net:   16384 bytes read in 4 ms (3.9 MiB/s)
131072 bytes read in 11 ms (11.4 MiB/s)
mtk-eth ethernet@15100000: MD32 firmware version: 24112802

Warning: ethernet@15100000 (eth0) using random MAC address - 1a:b4:08:ef:4e:eb
eth0: ethernet@15100000
Hit any key to stop autoboot:  0
BPI-R3M> ping $serverip
Using ethernet@15100000 device
host 192.168.0.11 is alive
BPI-R3M>

defconfig: r4: use dedicated r4 dts
defconfig: r4: enable ID_EEPROM as replacement for own tlv code
defconfig: r4pro: add tlv_eeprom and id_eeprom
uEnv: all: drop numbers from menu entries
they are added now by bootmenu after commit 8c986521c3c9
uenv: change from fatload to fs independ load
env: r3mini: add env for phy firmware
uenv: r3: add firmware loading script (not yet tested)
uenv: r4: add r4lite
uenv: r4: fix missing mmc overlay for emmc
uenv: r4: use own sd/emmc overlays for r4pro
uenv: r4: define additional bootconf (sata,wifi,pcie) with var addconf